#!/usr/bin/env python3
"""Generate IEEE 802.11 standard L-LTF matched filter taps"""

import numpy as np

# IEEE 802.11 standard L-LTF frequency domain sequence (52 non-zero subcarriers, -26 to +26)
LEGACY_LTF = (
    0,  # placeholder, not used
    1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1,  # SC +1 to +26
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  # Guard bands (indices 27-37)
    1, 1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1   # SC -26 to -1
)

# 1. Construct 64-point frequency domain array (all zeros)
freq_seq = np.zeros(64, dtype=complex)

# 2. Fill in 52 standard L-LTF values
# Positive frequencies: SC +1 to +26 -> bins 1 to 26
freq_seq[1:27] = LEGACY_LTF[1:27]
# Negative frequencies: SC -26 to -1 -> bins 38 to 63
freq_seq[38:64] = LEGACY_LTF[27:53]

# 3. Execute IFFT (shift=False, GNU Radio standard order)
time_seq = np.fft.ifft(freq_seq)

# 4. Generate matched filter taps: time reversal + conjugate
# FIR convolution equals correlation, need s*[-n]
taps = np.conj(time_seq[::-1])

# 5. Print C++ format array
print("// IEEE 802.11 L-LTF Matched Filter Taps (Generated from LEGACY_LTF)")
print("// DO NOT EDIT - Auto-generated by generate_long_template.py")
print("const std::vector<gr_complex> sync_long_impl::LONG = {")
for i, t in enumerate(taps):
    # Every 8 elements per line
    if i % 8 == 0:
        if i > 0:
            print("};")
        print("    // taps[{:02d}:{:02d}]".format(i, min(i+8, 64)))
    comma = "," if i < 63 else ""
    print(f"    gr_complex({t.real:+.10f}, {t.imag:+.10f}){comma}")
print("};")

# 6. Verification: check if imaginary parts are non-zero (should all be 0 for real sequence)
print(f"\n// Verification: taps has non-zero imaginary parts: {np.any(np.abs(np.imag(taps)) > 1e-9)}")
print(f"// Max imaginary: {np.max(np.abs(np.imag(taps))):.10f}")