/*
 * Copyright 2011, 2012 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ieee802-11
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ieee802_11/ht_symbol_splitter.h>

// pybind11 bindings for ht_symbol_splitter block

void bind_ht_symbol_splitter(py::module& m)
{
    using namespace gr::ieee802_11;

    py::class_<ht_symbol_splitter, gr::block, std::shared_ptr<ht_symbol_splitter>>(
        m, "ht_symbol_splitter", R"doc(
HT Symbol Splitter Block

Converts 80-sample HT-Mixed OFDM symbols to 64-sample FFT blocks.
This block removes the 16-sample cyclic prefix (CP) and outputs only
the 64-sample data portion, properly aligned for FFT processing.

HT-Mixed mode uses 80-sample OFDM symbols (16 CP + 64 data), but FFT blocks
are 64 samples. This block bridges that architectural mismatch.

Args:
    fft_size (int): FFT size (typically 64 for 20MHz)
    symbol_size (int): OFDM symbol size (80 for HT-Mixed, 64 for Legacy)
    cp_size (int): Cyclic prefix size (16 for HT-Mixed preamble)
)doc")
        .def(py::init(&ht_symbol_splitter::make),
             py::arg("fft_size") = 64,
             py::arg("symbol_size") = 80,
             py::arg("cp_size") = 16,
             R"doc(
Create an HT Symbol Splitter block.

Args:
    fft_size: FFT size (typically 64)
    symbol_size: OFDM symbol size (80 for HT-Mixed, 64 for Legacy)
    cp_size: Cyclic prefix size (16 for HT-Mixed)
)doc")
        .def("set_ht_mixed", &ht_symbol_splitter::set_ht_mixed,
             R"doc(
Set HT-Mixed mode.

Args:
    ht_mixed: True for HT-Mixed mode, False for Legacy mode
)doc");
}
