/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_short_fused.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b23899e2401a9b5e5b1cec2b5830bcf3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/sync_short_fused.h>
// pydoc.h is automatically generated in the build directory
#include <sync_short_fused_pydoc.h>

void bind_sync_short_fused(py::module& m)
{

    using sync_short_fused    = ::gr::ieee802_11::sync_short_fused;


    py::class_<sync_short_fused, gr::block, gr::basic_block,
        std::shared_ptr<sync_short_fused>>(m, "sync_short_fused", D(sync_short_fused))

        .def(py::init(&sync_short_fused::make),
           py::arg("threshold"),
           py::arg("energy_gate_factor") = 3.0,
           py::arg("noise_est_window") = 1024,
           D(sync_short_fused,make)
        )




        ;




}
